### ISSUE TITLE
Build site without deploying off master

### ISSUE THREAD

**Issue by tcbegley** [imrehg/cdei-development#17]
I think it would be helpful to have Actions build the site without deploying it on all branches. Just merged something and only found out on master that I had broken something 😳  (all fixed, don't worry)

**Comment by imrehg** [comment]
Yeah, this is in my plant to create a preview deployment, already have example of that in another project. Since we rely on github pages, it needs some extra setup (e.g. S3), but not a big deal.

In general I also do local builds to check, but yeah, the less effort it is, the better. Will set that up.

**Comment by tcbegley** [comment]
I've been building the website locally and all was good there, it was the figure generation pipeline failing because I screwed up the "if artifacts directory doesn't exist create it" step. I hadn't been testing the full generation pipeline from a clean directory locally. Maybe we can run that without requiring a preview site. Literally just run the pipeline, build the site, and don't put it anywhere.

**Comment by imrehg** [comment]
Done in #18, on each PR there will be a deployment where the preview build can be checked.
